-- ============================================================================
-- seed.sql — GENERADO AUTOMÁTICAMENTE. No lo edites a mano.
--
-- Fuente: packages/rules-engine/src/datos/*.ts
-- Regenerar: ver la sección "Regenerar seed.sql" de supabase/README.md
-- Versión del corpus legal: 2026.08.11
--
-- Es idempotente: se puede correr las veces que haga falta. Cada ejecución
-- deja rastro en content_revisions gracias a los triggers de la migración 0010,
-- que es exactamente lo que se quiere: sembrar también es un cambio.
-- ============================================================================

-- El motivo del cambio viaja en una variable de sesión y lo recoge el trigger
-- de versionado.
select set_config('app.motivo_cambio', 'Carga de datos semilla desde el motor jurídico 2026.08.11', false);

insert into public.legal_versions (version, published_at, valid_from, valid_to, description, is_current) values
  ('2026.08.11', '2026-08-11'::date, '2026-08-11'::date, null, 'Corpus legal compilado por LeyAntilavado.org: LFPIORPI vigente, reforma de julio de 2025, Reglamento reformado en marzo de 2026 y Acuerdo 115/2026.', true)
on conflict (version) do update set
  published_at = excluded.published_at,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  description = excluded.description,
  is_current = excluded.is_current;

insert into public.legal_sources (id, name, issuer, url, description, published_at, last_review_at) values
  ('lfpiorpi-vigente', 'Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita', 'Cámara de Diputados', 'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFPIORPI.pdf', 'Texto vigente de la ley, compilado por la Cámara de Diputados. Incluye la reforma publicada el 16 de julio de 2025.', '2025-07-16'::date, null),
  ('dof-reglamento-2026', 'Reforma al Reglamento de la LFPIORPI', 'DOF', 'https://dof.gob.mx/nota_detalle.php?codigo=5783547&fecha=27/03/2026', 'Decreto por el que se reforma el Reglamento de la LFPIORPI, publicado en el Diario Oficial de la Federación.', '2026-03-27'::date, null),
  ('dof-acuerdo-115-2026', 'Acuerdo 115/2026', 'DOF', 'https://dof.gob.mx/nota_detalle.php?codigo=5795797&fecha=07/08/2026', 'Acuerdo publicado en el Diario Oficial de la Federación el 7 de agosto de 2026, relacionado con las obligaciones en materia de prevención de lavado de dinero.', '2026-08-07'::date, null),
  ('sat-marco-normativo', 'Marco normativo PLD — SAT', 'SAT', 'https://sppld.sat.gob.mx/pld/interiores/marco.html', 'Compilación del marco normativo aplicable a actividades vulnerables publicada por el SAT.', null, null),
  ('sat-umbrales', 'Tabla de umbrales de identificación y aviso — SAT', 'SAT', 'https://sppld.sat.gob.mx/pld/interiores/umbrales.html', 'Tabla oficial del SAT con los umbrales de identificación y de aviso por actividad vulnerable.', null, null),
  ('sppld-portal', 'Portal de Prevención de Lavado de Dinero (SPPLD)', 'SAT', 'https://sppld.sat.gob.mx/', 'Portal donde los sujetos obligados se dan de alta, presentan avisos e informes en ceros.', null, null),
  ('inegi-uma', 'Unidad de Medida y Actualización (UMA) — INEGI', 'INEGI', 'https://www.inegi.org.mx/temas/uma/', 'Valores diario, mensual y anual de la UMA publicados por el INEGI. Entran en vigor el 1 de febrero de cada año.', null, null)
on conflict (id) do update set
  name = excluded.name,
  issuer = excluded.issuer,
  url = excluded.url,
  description = excluded.description,
  published_at = excluded.published_at,
  last_review_at = excluded.last_review_at;

insert into public.uma_values (year, daily_cents, valid_from, valid_to, source_ids, provision, verification, last_review_at, editorial_note, status) values
  (2016, 7304, '2016-02-01'::date, '2017-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2016 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2017, 7549, '2017-02-01'::date, '2018-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2017 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2018, 8060, '2018-02-01'::date, '2019-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2018 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2019, 8449, '2019-02-01'::date, '2020-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2019 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2020, 8688, '2020-02-01'::date, '2021-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2020 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2021, 8962, '2021-02-01'::date, '2022-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2021 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2022, 9622, '2022-02-01'::date, '2023-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2022 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2023, 10374, '2023-02-01'::date, '2024-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2023 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2024, 10857, '2024-02-01'::date, '2025-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2024 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2025, 11314, '2025-02-01'::date, '2026-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2025 publicado por el INEGI', 'fuente_secundaria', '2026-08-11'::date, 'Valor histórico pendiente de contraste directo contra el comunicado del INEGI del año correspondiente.', 'publicado'),
  (2026, 11731, '2026-02-01'::date, '2027-01-31'::date, array['inegi-uma']::text[], 'Valor de la UMA 2026 publicado por el INEGI', 'oficial_verificado', '2026-08-11'::date, null, 'publicado')
on conflict (year) do update set
  daily_cents = excluded.daily_cents,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  source_ids = excluded.source_ids,
  provision = excluded.provision,
  verification = excluded.verification,
  last_review_at = excluded.last_review_at,
  editorial_note = excluded.editorial_note,
  status = excluded.status;

insert into public.vulnerable_activities (slug, fraction, name, short_name, description, subject_examples, source_ids, provision, verification, last_review_at, editorial_note, status, sort_order) values
  ('juegos-sorteos', 'I', 'Juegos con apuesta, concursos y sorteos', 'Juegos y sorteos', 'Venta de boletos, fichas o cualquier comprobante para participar en juegos con apuesta, concursos o sorteos, así como el pago de premios. Aplica a organismos descentralizados y a quienes operan con permiso de la Secretaría de Gobernación.', array['Casinos y salas de sorteo de números','Operadores de loterías y rifas con permiso','Plataformas de apuestas en línea con permiso vigente','Empresas que organizan concursos con premio en efectivo']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción I', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 0),
  ('tarjetas-credito-servicios', 'II inciso a)', 'Emisión o comercialización de tarjetas de crédito o de servicios', 'Tarjetas de crédito y servicios', 'Emisión o comercialización habitual o profesional de tarjetas de crédito o de servicios por quien no es una entidad financiera. El umbral se mide sobre el gasto mensual acumulado en la cuenta, no por compra.', array['Tiendas departamentales con tarjeta propia','Cadenas con programas de crédito al consumo','Emisores de tarjetas de servicios no bancarias']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción II, inciso a)', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 1),
  ('tarjetas-prepagadas', 'II inciso b)', 'Emisión o comercialización de tarjetas prepagadas', 'Tarjetas prepagadas', 'Emisión, comercialización o abono de recursos en tarjetas prepagadas por quien no es entidad financiera. El umbral de identificación y el de aviso coinciden: toda operación que obliga a identificar también obliga a avisar.', array['Comercializadores de tarjetas de regalo con valor almacenado','Emisores de tarjetas prepagadas de uso general']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción II, inciso b)', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 2),
  ('vales-cupones-monederos', 'II inciso c)', 'Vales, cupones, monederos electrónicos y certificados', 'Vales y monederos', 'Emisión, comercialización o abono de recursos en instrumentos de almacenamiento de valor monetario distintos a las tarjetas: vales, cupones, monederos electrónicos y certificados.', array['Emisores de monederos electrónicos de despensa','Empresas de vales de gasolina o restaurante','Operadores de certificados de valor monetario']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción II, inciso c)', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 3),
  ('cheques-viajero', 'III', 'Emisión y comercialización de cheques de viajero', 'Cheques de viajero', 'Emisión y comercialización habitual o profesional de cheques de viajero por quien no es entidad financiera. Se identifica siempre, sin importar el monto.', array['Casas de cambio no financieras','Agencias de viaje que emiten cheques de viajero']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción III', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 4),
  ('prestamos-creditos', 'IV', 'Préstamos, créditos y mutuos sin ser entidad financiera', 'Préstamos y créditos', 'Ofrecimiento habitual o profesional de operaciones de mutuo, garantía, préstamo o crédito, con o sin garantía, por parte de quien no es una entidad financiera.', array['Casas de empeño','Financieras y prestamistas no regulados por la CNBV','Empresas que otorgan crédito de forma habitual a terceros']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción IV', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 5),
  ('inmuebles-construccion-intermediacion', 'V', 'Construcción, desarrollo e intermediación inmobiliaria', 'Inmobiliaria', 'Prestación habitual o profesional de servicios de construcción o desarrollo de inmuebles, o de intermediación en la transmisión de la propiedad o constitución de derechos sobre inmuebles, cuando hay operaciones de compraventa a favor de un cliente.', array['Inmobiliarias y brókers de bienes raíces','Constructoras que venden directamente al público','Plataformas de intermediación inmobiliaria']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción V', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 6),
  ('desarrollo-inmobiliario', 'V Bis', 'Recepción de recursos destinados a desarrollo inmobiliario', 'Desarrollo inmobiliario', 'Recepción de recursos destinados a un desarrollo inmobiliario cuya finalidad sea su venta o renta. Es la fracción más nueva de la ley: se adicionó por decreto publicado el 16 de julio de 2025 y alcanza esquemas de preventa y coinversión que antes no estaban nombrados.', array['Desarrolladoras que reciben aportaciones para preventa','Vehículos de coinversión inmobiliaria','Promotores que captan recursos de inversionistas para obra']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción V Bis (adicionada DOF 16-07-2025)', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 7),
  ('metales-joyeria', 'VI', 'Metales preciosos, piedras preciosas, joyería y relojes', 'Metales y joyería', 'Comercialización o intermediación habitual o profesional de metales preciosos, piedras preciosas, joyas o relojes. Es objeto de aviso con independencia de la forma de pago.', array['Joyerías','Compraventa de oro y plata','Relojerías de alta gama','Casas de subasta de joyas']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción VI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 8),
  ('obras-arte', 'VII', 'Subasta y comercialización de obras de arte', 'Obras de arte', 'Subasta o comercialización habitual o profesional de obras de arte cuando la operación alcanza el monto previsto por la ley.', array['Galerías de arte','Casas de subasta','Marchantes y agentes de artistas']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción VII', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 9),
  ('vehiculos', 'VIII', 'Comercialización de vehículos terrestres, marítimos y aéreos', 'Vehículos', 'Distribución y comercialización de todo tipo de vehículos, nuevos o usados, sean terrestres, marítimos o aéreos. Sólo es actividad vulnerable si se realiza de forma habitual o profesional.', array['Agencias automotrices','Lotes de autos usados','Vendedores de embarcaciones y aeronaves']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción VIII', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 10),
  ('blindaje', 'IX', 'Blindaje de vehículos e inmuebles', 'Blindaje', 'Prestación habitual o profesional de servicios de blindaje de vehículos terrestres o de bienes inmuebles.', array['Talleres de blindaje automotriz','Empresas de blindaje arquitectónico']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción IX', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 11),
  ('traslado-custodia-valores', 'X', 'Traslado o custodia de dinero o valores', 'Traslado de valores', 'Prestación habitual o profesional de servicios de traslado o custodia de dinero o valores. Cuando no es posible determinar el monto trasladado o custodiado, procede el aviso en todos los casos. Se exceptúa al Banco de México y a las instituciones de depósito de valores.', array['Empresas de transporte de valores','Servicios de custodia y bóveda']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción X', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 12),
  ('servicios-profesionales', 'XI', 'Servicios profesionales independientes', 'Servicios profesionales', 'Prestación de servicios profesionales de manera independiente, sin relación laboral, cuando se preparan o realizan para un cliente ciertos actos. El aviso no depende de un monto: procede cuando el profesional realiza, en nombre y representación del cliente, la operación financiera relacionada con el acto. La ley preserva el secreto profesional y la garantía de defensa.', array['Contadores públicos independientes','Abogados corporativos y fiscalistas','Consultores que administran recursos de terceros']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 13),
  ('fe-publica-notarios', 'XII Apartado A', 'Fe pública: notarios públicos', 'Notarios', 'Actos otorgados ante notario público. Cada inciso tiene su propia regla: unos tienen umbral en UMA y otros generan aviso siempre. La reforma de julio de 2025 endureció varios: el umbral de inmuebles bajó de 16,000 a 8,000 UMA, el de fideicomisos de 8,000 a 4,000, y la constitución de personas morales pasó de tener umbral a generar aviso siempre.', array['Notarías públicas']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado A', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 14),
  ('fe-publica-corredores', 'XII Apartado B', 'Fe pública: corredores públicos', 'Corredores públicos', 'Actos en los que interviene un corredor público. Los avalúos tienen umbral en UMA; los actos corporativos, fideicomisos y mutuos mercantiles generan aviso sin importar el monto.', array['Corredurías públicas']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado B', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 15),
  ('fe-publica-servidores-publicos', 'XII Apartado C', 'Fe pública: servidores públicos', 'Servidores públicos con fe pública', 'Servidores públicos a los que la ley confiere la facultad de dar fe pública en el ejercicio de sus atribuciones. La ley enuncia el apartado sin fijar umbrales propios y la tabla del SAT no lo desglosa.', array['Servidores públicos con facultad de dar fe pública conforme al art. 3, fracción VII, LFPIORPI']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado C', 'no_verificado', '2026-08-11'::date, 'La ley enuncia este apartado sin fijar umbrales y la tabla del SAT no lo incluye. No debe publicarse un umbral sin confirmación.', 'publicado', 16),
  ('personas-facilitadoras', 'XII Apartado D', 'Personas facilitadoras públicas y privadas', 'Personas facilitadoras', 'Apartado adicionado por la reforma publicada el 16 de julio de 2025. Alcanza a las personas facilitadoras previstas en la Ley General de Mecanismos Alternativos de Solución de Controversias y remite a los supuestos del Apartado A en los términos que la propia ley señala.', array['Personas facilitadoras públicas de centros de justicia alternativa','Personas facilitadoras privadas certificadas']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado D (adicionado DOF 16-07-2025)', 'no_verificado', '2026-08-11'::date, 'La ley enuncia este apartado sin fijar umbrales y la tabla del SAT no lo incluye. No debe publicarse un umbral sin confirmación.', 'publicado', 17),
  ('donativos', 'XIII', 'Donativos recibidos por asociaciones y sociedades sin fines de lucro', 'Donativos', 'Recepción de donativos por parte de asociaciones y sociedades sin fines de lucro, cuando alcanzan los montos previstos por la ley.', array['Asociaciones civiles','Fundaciones','Instituciones de asistencia privada']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIII', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 18),
  ('comercio-exterior', 'XIV', 'Comercio exterior: agentes y apoderados aduanales', 'Comercio exterior', 'Prestación de servicios de comercio exterior respecto de mercancías que la ley enumera. Cuatro de los seis incisos generan aviso cualquiera que sea el valor de los bienes; sólo joyería y obras de arte tienen umbral, y se mide por el valor individual del bien, no por el pedimento completo.', array['Agencias aduanales','Apoderados aduanales','Agentes aduanales']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIV', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 19),
  ('arrendamiento-inmuebles', 'XV', 'Arrendamiento y derechos de uso o goce de inmuebles', 'Arrendamiento', 'Constitución de derechos personales de uso o goce de bienes inmuebles. El umbral se mide sobre el valor mensual, al día en que se realiza el pago o se cumple la obligación. Ojo al matiz: la identificación aplica cuando la renta es superior a 1,605 UMA, y el aviso cuando es igual o superior a 3,210 UMA.', array['Arrendadores de locales comerciales y oficinas','Administradoras de propiedades en renta','Operadores de naves industriales','Propietarios que rentan de forma habitual']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XV', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 20),
  ('activos-virtuales', 'XVI', 'Intercambio de activos virtuales', 'Activos virtuales', 'Ofrecimiento habitual y profesional de intercambio de activos virtuales por sujetos distintos a las entidades financieras, a través de plataformas electrónicas. Alcanza también las operaciones realizadas con ciudadanos mexicanos desde otra jurisdicción. Tiene dos disparadores independientes: el monto de la operación y la contraprestación cobrada por el servicio.', array['Plataformas de intercambio de criptoactivos no reguladas como ITF','Operadores de compraventa de activos virtuales','Cajeros de criptomonedas']::text[], array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XVI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado', 21)
on conflict (slug) do update set
  fraction = excluded.fraction,
  name = excluded.name,
  short_name = excluded.short_name,
  description = excluded.description,
  subject_examples = excluded.subject_examples,
  source_ids = excluded.source_ids,
  provision = excluded.provision,
  verification = excluded.verification,
  last_review_at = excluded.last_review_at,
  editorial_note = excluded.editorial_note,
  status = excluded.status,
  sort_order = excluded.sort_order;

insert into public.activity_subtypes (activity_slug, slug, name, description) values
  ('servicios-profesionales', 'compraventa-inmuebles', 'Compraventa de inmuebles o cesión de derechos', 'Preparación o realización de la compraventa de bienes inmuebles o la cesión de derechos sobre éstos.'),
  ('servicios-profesionales', 'administracion-recursos', 'Administración y manejo de recursos y activos', 'Administración y manejo de recursos, valores o cualquier otro activo del cliente.'),
  ('servicios-profesionales', 'cuentas-bancarias', 'Manejo de cuentas bancarias, de ahorro o de valores', 'Manejo de cuentas bancarias, de ahorro o de valores del cliente.'),
  ('servicios-profesionales', 'aportaciones-capital', 'Organización de aportaciones de capital', 'Organización de aportaciones de capital o recursos para la constitución, operación y administración de sociedades mercantiles.'),
  ('servicios-profesionales', 'constitucion-personas-morales', 'Constitución y administración de personas morales', 'Constitución, escisión, fusión, operación y administración de personas morales o vehículos corporativos, incluido el fideicomiso y la compraventa de entidades mercantiles.'),
  ('fe-publica-notarios', 'inmuebles', 'Derechos reales sobre inmuebles', 'Transmisión o constitución de derechos reales sobre inmuebles. La base es el valor más alto entre precio pactado, valor catastral, valor comercial o monto garantizado por suerte principal.'),
  ('fe-publica-notarios', 'poderes-irrevocables', 'Poderes irrevocables', 'Otorgamiento de poderes para actos de administración o dominio con carácter irrevocable.'),
  ('fe-publica-notarios', 'constitucion-personas-morales', 'Constitución y modificación de personas morales', 'Constitución de personas morales, modificación patrimonial por aumento o disminución de capital, fusión o escisión, y compraventa de acciones y partes sociales.'),
  ('fe-publica-notarios', 'fideicomisos', 'Fideicomisos traslativos o de garantía', 'Constitución o modificación de fideicomisos traslativos de dominio o de garantía, salvo los constituidos a favor de instituciones del sistema financiero u organismos públicos de vivienda.'),
  ('fe-publica-notarios', 'mutuo-credito', 'Mutuos y créditos', 'Otorgamiento de contratos de mutuo o crédito, con o sin garantía, cuando el acreedor no forma parte del sistema financiero ni es organismo público de vivienda.'),
  ('fe-publica-corredores', 'avaluos', 'Avalúos', 'Realización de avalúos sobre bienes.'),
  ('fe-publica-corredores', 'constitucion-sociedades', 'Constitución y modificación de sociedades mercantiles', 'Constitución de personas morales mercantiles, modificación patrimonial, fusión o escisión, y compraventa de acciones y partes sociales.'),
  ('fe-publica-corredores', 'fideicomisos', 'Fideicomisos', 'Constitución, modificación o cesión de derechos de fideicomisos en los que puedan actuar, salvo los constituidos para garantizar crédito a favor del sistema financiero.'),
  ('fe-publica-corredores', 'mutuo-mercantil', 'Mutuos y créditos mercantiles', 'Otorgamiento de contratos de mutuo mercantil o créditos mercantiles cuando el acreedor no forma parte del sistema financiero.'),
  ('comercio-exterior', 'vehiculos', 'Vehículos terrestres, aéreos y marítimos', 'Importación o exportación de vehículos, nuevos y usados, cualquiera que sea su valor.'),
  ('comercio-exterior', 'maquinas-juegos', 'Máquinas para juegos de apuesta y sorteos', 'Máquinas para juego con apuesta y sorteos, nuevas y usadas, cualquiera que sea su valor.'),
  ('comercio-exterior', 'equipos-tarjetas-pago', 'Equipos y materiales para tarjetas de pago', 'Equipos y materiales para la elaboración de tarjetas de pago, cualquiera que sea su valor.'),
  ('comercio-exterior', 'joyas-metales', 'Joyas, relojes, piedras y metales preciosos', 'Importación o exportación de joyas, relojes, piedras preciosas y metales preciosos. El umbral se mide por el valor individual del bien.'),
  ('comercio-exterior', 'obras-arte', 'Obras de arte', 'Importación o exportación de obras de arte. El umbral se mide por el valor individual del bien.'),
  ('comercio-exterior', 'material-balistico', 'Materiales de resistencia balística', 'Materiales de resistencia balística para blindaje de vehículos, cualquiera que sea su valor.'),
  ('activos-virtuales', 'monto-operacion', 'Monto de la operación', 'Monto de la operación de intercambio por cliente o usuario.'),
  ('activos-virtuales', 'contraprestacion', 'Contraprestación cobrada', 'Contraprestación cobrada por el servicio, cualquiera que sea su denominación.')
on conflict (activity_slug, slug) do update set
  name = excluded.name,
  description = excluded.description;

insert into public.threshold_rules (id, activity_slug, subtype, identification_spec, notice_spec, periodicity, valid_from, valid_to, source_ids, provision, verification, last_review_at, reviewed_by, editorial_note, status) values
  ('juegos-sorteos', 'juegos-sorteos', null, '{"tipo":"uma","uma":325}'::jsonb, '{"tipo":"uma","uma":645}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción I', 'oficial_verificado', '2026-08-11'::date, null, 'Aplica a la operación individual o a series de transacciones vinculadas entre sí en apariencia.', 'publicado'),
  ('tarjetas-credito-servicios', 'tarjetas-credito-servicios', null, '{"tipo":"uma","uma":805,"nota":"Medido sobre el gasto mensual acumulado en la cuenta de la tarjeta."}'::jsonb, '{"tipo":"uma","uma":1285,"nota":"Medido sobre el gasto mensual acumulado en la cuenta de la tarjeta."}'::jsonb, 'mensual', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción II, inciso a)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('tarjetas-prepagadas', 'tarjetas-prepagadas', null, '{"tipo":"uma","uma":645}'::jsonb, '{"tipo":"uma","uma":645}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción II, inciso b)', 'oficial_verificado', '2026-08-11'::date, null, 'Se mide por operación de comercialización o abono de recursos. Los umbrales de identificación y aviso coinciden.', 'publicado'),
  ('vales-cupones-monederos', 'vales-cupones-monederos', null, '{"tipo":"uma","uma":645}'::jsonb, '{"tipo":"uma","uma":645}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción II, inciso c)', 'oficial_verificado', '2026-08-11'::date, null, 'Se mide por operación de emisión, comercialización o abono de recursos. Los umbrales coinciden.', 'publicado'),
  ('cheques-viajero', 'cheques-viajero', null, '{"tipo":"siempre","nota":"Se identifica a quien adquiere cheques de viajero sin importar el monto."}'::jsonb, '{"tipo":"uma","uma":645}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción III', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('prestamos-creditos', 'prestamos-creditos', null, '{"tipo":"siempre","nota":"Toda operación de mutuo, préstamo, crédito o garantía exige identificar al cliente."}'::jsonb, '{"tipo":"uma","uma":1605}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción IV', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('inmuebles-construccion-intermediacion', 'inmuebles-construccion-intermediacion', null, '{"tipo":"siempre","nota":"La intermediación y el desarrollo inmobiliario exigen identificar siempre al cliente."}'::jsonb, '{"tipo":"uma","uma":8025}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción V', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('desarrollo-inmobiliario', 'desarrollo-inmobiliario', null, '{"tipo":"siempre"}'::jsonb, '{"tipo":"uma","uma":8025}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción V Bis (adicionada DOF 16-07-2025)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('metales-joyeria', 'metales-joyeria', null, '{"tipo":"uma","uma":805}'::jsonb, '{"tipo":"uma","uma":1605}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción VI', 'oficial_verificado', '2026-08-11'::date, null, 'Es objeto de aviso con independencia de la forma de pago. Se exceptúan las operaciones en que interviene el Banco de México.', 'publicado'),
  ('obras-arte', 'obras-arte', null, '{"tipo":"uma","uma":2410}'::jsonb, '{"tipo":"uma","uma":4815}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción VII', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('vehiculos', 'vehiculos', null, '{"tipo":"uma","uma":3210}'::jsonb, '{"tipo":"uma","uma":6420}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción VIII', 'oficial_verificado', '2026-08-11'::date, null, 'Sólo constituye actividad vulnerable cuando la distribución o comercialización es habitual o profesional.', 'publicado'),
  ('blindaje', 'blindaje', null, '{"tipo":"uma","uma":2410}'::jsonb, '{"tipo":"uma","uma":4815}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción IX', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('traslado-custodia-valores', 'traslado-custodia-valores', null, '{"tipo":"siempre"}'::jsonb, '{"tipo":"variable","nota":"Hay dos supuestos: uno con umbral y otro que obliga siempre cuando el monto no puede determinarse.","supuestos":[{"clave":"monto-determinable","descripcion":"Es posible determinar el monto del dinero o de los valores trasladados o custodiados.","umbral":{"tipo":"uma","uma":3210}},{"clave":"monto-indeterminable","descripcion":"No es posible determinar el monto del dinero o los valores.","umbral":{"tipo":"siempre","nota":"Procede el aviso en todos los casos, sin importar el valor."}}]}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción X', 'oficial_verificado', '2026-08-11'::date, null, 'Se exceptúan el Banco de México y las instituciones de depósito de valores.', 'publicado'),
  ('servicios-profesionales--compraventa-inmuebles', 'servicios-profesionales', 'compraventa-inmuebles', '{"tipo":"siempre","nota":"Se identifica al cliente siempre que se prepare o realice el acto, sin importar el monto."}'::jsonb, '{"tipo":"variable","nota":"El aviso no tiene umbral monetario: procede cuando el profesional realiza la operación financiera en nombre y representación del cliente.","supuestos":[{"clave":"en-representacion","descripcion":"El profesional realiza, en nombre y representación del cliente, la operación financiera relacionada con el acto.","umbral":{"tipo":"siempre","nota":"Procede el aviso, sin umbral monetario."}},{"clave":"solo-asesoria","descripcion":"El profesional únicamente asesora, opina o prepara documentos, sin realizar la operación en nombre del cliente.","umbral":{"tipo":"nunca","nota":"No procede el aviso por este supuesto, pero subsisten las obligaciones de identificar al cliente e integrar expediente."}}]}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XI, inciso a)', 'oficial_verificado', '2026-08-11'::date, null, 'La ley preserva el secreto profesional y la garantía de defensa del cliente.', 'publicado'),
  ('servicios-profesionales--administracion-recursos', 'servicios-profesionales', 'administracion-recursos', '{"tipo":"siempre","nota":"Se identifica al cliente siempre que se prepare o realice el acto, sin importar el monto."}'::jsonb, '{"tipo":"variable","nota":"El aviso no tiene umbral monetario: procede cuando el profesional realiza la operación financiera en nombre y representación del cliente.","supuestos":[{"clave":"en-representacion","descripcion":"El profesional realiza, en nombre y representación del cliente, la operación financiera relacionada con el acto.","umbral":{"tipo":"siempre","nota":"Procede el aviso, sin umbral monetario."}},{"clave":"solo-asesoria","descripcion":"El profesional únicamente asesora, opina o prepara documentos, sin realizar la operación en nombre del cliente.","umbral":{"tipo":"nunca","nota":"No procede el aviso por este supuesto, pero subsisten las obligaciones de identificar al cliente e integrar expediente."}}]}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XI, inciso b)', 'oficial_verificado', '2026-08-11'::date, null, 'La ley preserva el secreto profesional y la garantía de defensa del cliente.', 'publicado'),
  ('servicios-profesionales--cuentas-bancarias', 'servicios-profesionales', 'cuentas-bancarias', '{"tipo":"siempre","nota":"Se identifica al cliente siempre que se prepare o realice el acto, sin importar el monto."}'::jsonb, '{"tipo":"variable","nota":"El aviso no tiene umbral monetario: procede cuando el profesional realiza la operación financiera en nombre y representación del cliente.","supuestos":[{"clave":"en-representacion","descripcion":"El profesional realiza, en nombre y representación del cliente, la operación financiera relacionada con el acto.","umbral":{"tipo":"siempre","nota":"Procede el aviso, sin umbral monetario."}},{"clave":"solo-asesoria","descripcion":"El profesional únicamente asesora, opina o prepara documentos, sin realizar la operación en nombre del cliente.","umbral":{"tipo":"nunca","nota":"No procede el aviso por este supuesto, pero subsisten las obligaciones de identificar al cliente e integrar expediente."}}]}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XI, inciso c)', 'oficial_verificado', '2026-08-11'::date, null, 'La ley preserva el secreto profesional y la garantía de defensa del cliente.', 'publicado'),
  ('servicios-profesionales--aportaciones-capital', 'servicios-profesionales', 'aportaciones-capital', '{"tipo":"siempre","nota":"Se identifica al cliente siempre que se prepare o realice el acto, sin importar el monto."}'::jsonb, '{"tipo":"variable","nota":"El aviso no tiene umbral monetario: procede cuando el profesional realiza la operación financiera en nombre y representación del cliente.","supuestos":[{"clave":"en-representacion","descripcion":"El profesional realiza, en nombre y representación del cliente, la operación financiera relacionada con el acto.","umbral":{"tipo":"siempre","nota":"Procede el aviso, sin umbral monetario."}},{"clave":"solo-asesoria","descripcion":"El profesional únicamente asesora, opina o prepara documentos, sin realizar la operación en nombre del cliente.","umbral":{"tipo":"nunca","nota":"No procede el aviso por este supuesto, pero subsisten las obligaciones de identificar al cliente e integrar expediente."}}]}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XI, inciso d)', 'oficial_verificado', '2026-08-11'::date, null, 'La ley preserva el secreto profesional y la garantía de defensa del cliente.', 'publicado'),
  ('servicios-profesionales--constitucion-personas-morales', 'servicios-profesionales', 'constitucion-personas-morales', '{"tipo":"siempre","nota":"Se identifica al cliente siempre que se prepare o realice el acto, sin importar el monto."}'::jsonb, '{"tipo":"variable","nota":"El aviso no tiene umbral monetario: procede cuando el profesional realiza la operación financiera en nombre y representación del cliente.","supuestos":[{"clave":"en-representacion","descripcion":"El profesional realiza, en nombre y representación del cliente, la operación financiera relacionada con el acto.","umbral":{"tipo":"siempre","nota":"Procede el aviso, sin umbral monetario."}},{"clave":"solo-asesoria","descripcion":"El profesional únicamente asesora, opina o prepara documentos, sin realizar la operación en nombre del cliente.","umbral":{"tipo":"nunca","nota":"No procede el aviso por este supuesto, pero subsisten las obligaciones de identificar al cliente e integrar expediente."}}]}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XI, inciso e)', 'oficial_verificado', '2026-08-11'::date, null, 'La ley preserva el secreto profesional y la garantía de defensa del cliente.', 'publicado'),
  ('fe-publica-notarios--inmuebles', 'fe-publica-notarios', 'inmuebles', '{"tipo":"siempre"}'::jsonb, '{"tipo":"uma","uma":8000,"nota":"La base es el valor más alto entre el precio pactado, el valor catastral, el valor comercial y el monto garantizado por suerte principal."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado A, inciso a)', 'oficial_verificado', '2026-08-11'::date, null, 'La reforma del 16-07-2025 bajó este umbral de 16,000 a 8,000 UMA. Se exceptúan las garantías a favor de instituciones del sistema financiero u organismos públicos de vivienda.', 'publicado'),
  ('fe-publica-notarios--poderes-irrevocables', 'fe-publica-notarios', 'poderes-irrevocables', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre","nota":"Los poderes irrevocables para actos de administración o dominio son siempre objeto de aviso."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado A, inciso b)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('fe-publica-notarios--constitucion-personas-morales', 'fe-publica-notarios', 'constitucion-personas-morales', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre","nota":"La constitución de personas morales, los cambios de capital, las fusiones, escisiones y la compraventa de acciones o partes sociales son siempre objeto de aviso."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado A, inciso c)', 'oficial_verificado', '2026-08-11'::date, null, 'La reforma del 16-07-2025 eliminó el umbral de 8,000 UMA que existía: ahora el aviso procede siempre.', 'publicado'),
  ('fe-publica-notarios--fideicomisos', 'fe-publica-notarios', 'fideicomisos', '{"tipo":"siempre"}'::jsonb, '{"tipo":"uma","uma":4000}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado A, inciso d)', 'oficial_verificado', '2026-08-11'::date, null, 'La reforma del 16-07-2025 bajó este umbral de 8,000 a 4,000 UMA. Se exceptúan los fideicomisos constituidos para garantizar crédito a favor del sistema financiero u organismos públicos de vivienda.', 'publicado'),
  ('fe-publica-notarios--mutuo-credito', 'fe-publica-notarios', 'mutuo-credito', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre","nota":"Los mutuos y créditos otorgados ante notario son siempre objeto de aviso."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado A, inciso e)', 'oficial_verificado', '2026-08-11'::date, null, 'Aplica cuando el acreedor no forma parte del sistema financiero ni es organismo público de vivienda.', 'publicado'),
  ('fe-publica-corredores--avaluos', 'fe-publica-corredores', 'avaluos', '{"tipo":"uma","uma":8025}'::jsonb, '{"tipo":"uma","uma":8025}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado B, inciso a)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('fe-publica-corredores--constitucion-sociedades', 'fe-publica-corredores', 'constitucion-sociedades', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre"}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado B, inciso b)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('fe-publica-corredores--fideicomisos', 'fe-publica-corredores', 'fideicomisos', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre"}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado B, inciso c)', 'oficial_verificado', '2026-08-11'::date, null, 'Se exceptúan los constituidos para garantizar crédito a favor de instituciones del sistema financiero.', 'publicado'),
  ('fe-publica-corredores--mutuo-mercantil', 'fe-publica-corredores', 'mutuo-mercantil', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre"}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XII, Apartado B, inciso d)', 'oficial_verificado', '2026-08-11'::date, null, 'Aplica cuando el acreedor no forma parte del sistema financiero.', 'publicado'),
  ('fe-publica-servidores-publicos', 'fe-publica-servidores-publicos', null, '{"tipo":"requiere_revision","nota":"Sin umbral publicado por la autoridad."}'::jsonb, '{"tipo":"requiere_revision","nota":"Sin umbral publicado por la autoridad."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 17, fracción XII, Apartado C', 'no_verificado', '2026-08-11'::date, null, 'La ley enuncia el apartado sin fijar umbrales y la tabla oficial de umbrales del SAT no lo incluye. No debe publicarse una cifra sin confirmación de la autoridad.', 'borrador'),
  ('personas-facilitadoras', 'personas-facilitadoras', null, '{"tipo":"requiere_revision","nota":"Sin umbral publicado por la autoridad."}'::jsonb, '{"tipo":"requiere_revision","nota":"Sin umbral publicado por la autoridad."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 17, fracción XII, Apartado D (adicionado DOF 16-07-2025)', 'no_verificado', '2026-08-11'::date, null, 'Apartado nuevo que remite a los supuestos del Apartado A "en los términos que se señalan". No aparece en la tabla del SAT. Requiere revisión editorial antes de publicar umbrales.', 'borrador'),
  ('donativos', 'donativos', null, '{"tipo":"uma","uma":1605}'::jsonb, '{"tipo":"uma","uma":3210}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIII', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('comercio-exterior--vehiculos', 'comercio-exterior', 'vehiculos', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre","nota":"Vehículos terrestres, aéreos y marítimos, nuevos y usados. Genera aviso cualquiera que sea el valor de los bienes."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIV, inciso a)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('comercio-exterior--maquinas-juegos', 'comercio-exterior', 'maquinas-juegos', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre","nota":"Máquinas para juegos de apuesta y sorteos, nuevas y usadas. Genera aviso cualquiera que sea el valor de los bienes."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIV, inciso b)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('comercio-exterior--equipos-tarjetas-pago', 'comercio-exterior', 'equipos-tarjetas-pago', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre","nota":"Equipos y materiales para la elaboración de tarjetas de pago. Genera aviso cualquiera que sea el valor de los bienes."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIV, inciso c)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('comercio-exterior--material-balistico', 'comercio-exterior', 'material-balistico', '{"tipo":"siempre"}'::jsonb, '{"tipo":"siempre","nota":"Materiales de resistencia balística para blindaje de vehículos. Genera aviso cualquiera que sea el valor de los bienes."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIV, inciso f)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('comercio-exterior--joyas-metales', 'comercio-exterior', 'joyas-metales', '{"tipo":"uma","uma":485,"nota":"El umbral se mide por el valor individual del bien, no por el pedimento completo."}'::jsonb, '{"tipo":"uma","uma":485,"nota":"El umbral se mide por el valor individual del bien, no por el pedimento completo."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIV, inciso d)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('comercio-exterior--obras-arte', 'comercio-exterior', 'obras-arte', '{"tipo":"uma","uma":4815,"nota":"El umbral se mide por el valor individual del bien."}'::jsonb, '{"tipo":"uma","uma":4815,"nota":"El umbral se mide por el valor individual del bien."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XIV, inciso e)', 'oficial_verificado', '2026-08-11'::date, null, 'Contrastado contra la tabla oficial de umbrales del SAT y el texto vigente de la LFPIORPI (última reforma DOF 16-07-2025).', 'publicado'),
  ('arrendamiento-inmuebles', 'arrendamiento-inmuebles', null, '{"tipo":"uma","uma":1605,"comparador":"mayor","nota":"La ley dice \"superior a\": una renta mensual de exactamente 1,605 UMA no alcanza el umbral de identificación."}'::jsonb, '{"tipo":"uma","uma":3210,"nota":"La ley dice \"igual o superior a\": una renta mensual de exactamente 3,210 UMA sí alcanza el umbral de aviso."}'::jsonb, 'mensual', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XV', 'oficial_verificado', '2026-08-11'::date, null, 'El valor se mide de forma mensual, al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('activos-virtuales', 'activos-virtuales', null, '{"tipo":"siempre","nota":"Toda operación de intercambio de activos virtuales exige identificar al cliente."}'::jsonb, '{"tipo":"monto_o_comision","umaMonto":210,"umaComision":4,"nota":"Hay dos disparadores independientes: el monto de la operación por cliente (210 UMA) y la contraprestación cobrada por el servicio (4 UMA). Basta con que uno se alcance."}'::jsonb, 'operacion', '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 17, fracción XVI, incisos a) y b)', 'oficial_verificado', '2026-08-11'::date, null, 'Alcanza también operaciones realizadas con ciudadanos mexicanos desde otra jurisdicción.', 'publicado')
on conflict (id) do update set
  activity_slug = excluded.activity_slug,
  subtype = excluded.subtype,
  identification_spec = excluded.identification_spec,
  notice_spec = excluded.notice_spec,
  periodicity = excluded.periodicity,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  source_ids = excluded.source_ids,
  provision = excluded.provision,
  verification = excluded.verification,
  last_review_at = excluded.last_review_at,
  reviewed_by = excluded.reviewed_by,
  editorial_note = excluded.editorial_note,
  status = excluded.status;

-- Reglas de acumulación del corpus (organization_id nulo = aplican a todas).
insert into public.accumulation_rules (threshold_rule_id, organization_id, applies, window_months, group_by, note, source_ids)
values
  ('juegos-sorteos', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('tarjetas-credito-servicios', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('tarjetas-prepagadas', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('vales-cupones-monederos', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('cheques-viajero', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('prestamos-creditos', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('inmuebles-construccion-intermediacion', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('desarrollo-inmobiliario', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('metales-joyeria', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('obras-arte', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('vehiculos', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('blindaje', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('traslado-custodia-valores', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('fe-publica-notarios--inmuebles', null, true, 6, array['cliente','actividad','subtipo']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('fe-publica-notarios--fideicomisos', null, true, 6, array['cliente','actividad','subtipo']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('fe-publica-corredores--avaluos', null, true, 6, array['cliente','actividad','subtipo']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('donativos', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('comercio-exterior--joyas-metales', null, true, 6, array['cliente','actividad','subtipo']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('comercio-exterior--obras-arte', null, true, 6, array['cliente','actividad','subtipo']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('arrendamiento-inmuebles', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[]),
  ('activos-virtuales', null, true, 6, array['cliente','actividad']::text[], 'Regla antifraccionamiento del art. 17, último párrafo: se suman las operaciones del mismo cliente por el mismo tipo de acto realizadas en seis meses.', array['lfpiorpi-vigente','sat-umbrales']::text[])
on conflict do nothing;

insert into public.cash_restriction_rules (id, slug, name, description, activities, limit_uma, periodicity, discrepancy, valid_from, valid_to, source_ids, provision, verification, last_review_at, editorial_note, status) values
  ('efectivo-inmuebles', 'inmuebles', 'Constitución o transmisión de derechos reales sobre inmuebles', 'Compraventa de inmuebles y demás actos que constituyen o transmiten derechos reales sobre ellos.', array['inmuebles-construccion-intermediacion','desarrollo-inmobiliario','fe-publica-notarios']::text[], 8025, 'operacion', null, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el art. 32 de la LFPIORPI vigente y la tabla del SAT. Los montos se miden al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('efectivo-vehiculos', 'vehiculos', 'Vehículos nuevos o usados: terrestres, marítimos y aéreos', 'Transmisión de propiedad o constitución de derechos reales sobre vehículos de cualquier tipo, nuevos o usados.', array['vehiculos']::text[], 3210, 'operacion', null, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el art. 32 de la LFPIORPI vigente y la tabla del SAT. Los montos se miden al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('efectivo-relojes-joyeria-arte', 'relojes-joyeria-arte', 'Relojes, joyería, metales, piedras preciosas y obras de arte', 'Transmisión de propiedad de relojes, joyería, metales preciosos y piedras preciosas, así como de obras de arte. El límite aplica por pieza o por lote.', array['metales-joyeria','obras-arte']::text[], 3210, 'operacion', null, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el art. 32 de la LFPIORPI vigente y la tabla del SAT. Los montos se miden al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('efectivo-juegos-apuesta', 'juegos-apuesta', 'Boletos de juegos con apuesta y pago de premios', 'Adquisición de boletos para participar en juegos con apuesta, concursos o sorteos, así como la entrega o pago de los premios.', array['juegos-sorteos']::text[], 3210, 'operacion', null, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el art. 32 de la LFPIORPI vigente y la tabla del SAT. Los montos se miden al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('efectivo-blindaje', 'blindaje', 'Servicios de blindaje', 'Prestación de servicios de blindaje para vehículos o para bienes inmuebles.', array['blindaje']::text[], 3210, 'operacion', null, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el art. 32 de la LFPIORPI vigente y la tabla del SAT. Los montos se miden al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('efectivo-acciones-partes-sociales', 'acciones-partes-sociales', 'Acciones y partes sociales', 'Transmisión de dominio o constitución de derechos sobre títulos representativos de partes sociales o acciones de personas morales.', array['fe-publica-notarios','fe-publica-corredores','servicios-profesionales']::text[], 3210, 'operacion', null, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el art. 32 de la LFPIORPI vigente y la tabla del SAT. Los montos se miden al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('efectivo-arrendamiento', 'arrendamiento', 'Arrendamiento de inmuebles, vehículos y bienes blindados', 'Constitución de derechos personales de uso o goce sobre inmuebles, vehículos y bienes blindados. El límite se mide de forma mensual.', array['arrendamiento-inmuebles']::text[], 3210, 'mensual', null, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el art. 32 de la LFPIORPI vigente y la tabla del SAT. Los montos se miden al día en que se realiza el pago o se cumple la obligación.', 'publicado'),
  ('efectivo-consignacion-pago', 'consignacion-pago', 'Consignación de pago', 'Consignación de pago relacionada con cualquiera de los actos u operaciones anteriores. Fracción adicionada por la reforma publicada el 16 de julio de 2025.', '{}', 3210, 'operacion', '{"descripcion":"Dos fuentes oficiales publican reglas distintas para este supuesto. Mientras la autoridad no lo aclare, la herramienta muestra ambas y no calcula un resultado definitivo.","segunSAT":"La tabla del SAT publica un límite fijo de 3,210 UMA.","segunLey":"El texto de la ley remite al umbral de la fracción con la que se relaciona la consignación: 8,025 UMA si es sobre inmuebles y 3,210 UMA en los demás casos."}'::jsonb, '2025-07-17'::date, null, array['lfpiorpi-vigente','sat-umbrales']::text[], 'Art. 32 LFPIORPI', 'no_verificado', '2026-08-11'::date, 'Existe una contradicción entre la tabla del SAT y el texto de la ley. Requiere revisión editorial antes de publicarse como regla firme.', 'borrador')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  description = excluded.description,
  activities = excluded.activities,
  limit_uma = excluded.limit_uma,
  periodicity = excluded.periodicity,
  discrepancy = excluded.discrepancy,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  source_ids = excluded.source_ids,
  provision = excluded.provision,
  verification = excluded.verification,
  last_review_at = excluded.last_review_at,
  editorial_note = excluded.editorial_note,
  status = excluded.status;

insert into public.sanctions (id, article, fraction, scenario, min_uma, max_uma, min_percent, max_percent, severity, notes, valid_from, valid_to, source_ids, provision, verification, last_review_at, editorial_note, status) values
  ('art54-I--53-I', '54', 'I', 'No cumplir con los requerimientos que formule la autoridad competente (art. 53, fracción I).', 200, 2000, null, null, 'media', null, '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 54, fracción I, en relación con el art. 53, fracción I', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el texto de la LFPIORPI publicado por la Cámara de Diputados (DOF 16-07-2025).', 'publicado'),
  ('art54-I--53-II', '54', 'I', 'No cumplir con las obligaciones de identificar al cliente o usuario, integrar el expediente o conservar la información (art. 53, fracción II).', 200, 2000, null, null, 'alta', null, '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 54, fracción I, en relación con el art. 53, fracción II', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el texto de la LFPIORPI publicado por la Cámara de Diputados (DOF 16-07-2025).', 'publicado'),
  ('art54-I--53-III', '54', 'I', 'Presentar los avisos de forma extemporánea, incompleta o sin cumplir los requisitos aplicables (art. 53, fracción III).', 200, 2000, null, null, 'alta', 'El texto vigente remite la extemporaneidad mayor a 30 días a la fracción II del art. 54. Existe una posible imprecisión legislativa en esa remisión: el caso concreto requiere análisis jurídico.', '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 54, fracción I, en relación con el art. 53, fracción III', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el texto de la LFPIORPI publicado por la Cámara de Diputados (DOF 16-07-2025).', 'publicado'),
  ('art54-I--53-IV', '54', 'I', 'Incumplir cualquiera de las demás obligaciones de la ley (art. 53, fracción IV).', 200, 2000, null, null, 'media', null, '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 54, fracción I, en relación con el art. 53, fracción IV', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el texto de la LFPIORPI publicado por la Cámara de Diputados (DOF 16-07-2025).', 'publicado'),
  ('art54-II--53-V', '54', 'II', 'Incumplir las obligaciones previstas en los arts. 33, 33 Bis y 33 Ter, relativas al uso de la información y al régimen del representante encargado del cumplimiento (art. 53, fracción V).', 2000, 10000, null, null, 'alta', null, '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 54, fracción II, en relación con el art. 53, fracción V', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el texto de la LFPIORPI publicado por la Cámara de Diputados (DOF 16-07-2025).', 'publicado'),
  ('art54-III--53-VI', '54', 'III', 'Omitir la presentación de los avisos (art. 53, fracción VI).', 10000, 65000, 10, 100, 'critica', 'Se aplica la cantidad que resulte MAYOR entre el rango en UMA y el porcentaje del valor del acto. El porcentaje sólo procede cuando el acto u operación es cuantificable en dinero; si no lo es, queda únicamente el rango en UMA.', '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 54, fracción III, en relación con el art. 53, fracción VI', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el texto de la LFPIORPI publicado por la Cámara de Diputados (DOF 16-07-2025).', 'publicado'),
  ('art54-III--53-VII', '54', 'III', 'Realizar operaciones liquidadas en efectivo o metales por encima de los límites del art. 32 (art. 53, fracción VII).', 10000, 65000, 10, 100, 'critica', 'Se aplica la cantidad que resulte MAYOR entre el rango en UMA y el porcentaje del valor del acto, cuando éste sea cuantificable en dinero.', '2025-07-17'::date, null, array['lfpiorpi-vigente']::text[], 'Art. 54, fracción III, en relación con el art. 53, fracción VII', 'oficial_verificado', '2026-08-11'::date, 'Contrastado contra el texto de la LFPIORPI publicado por la Cámara de Diputados (DOF 16-07-2025).', 'publicado')
on conflict (id) do update set
  article = excluded.article,
  fraction = excluded.fraction,
  scenario = excluded.scenario,
  min_uma = excluded.min_uma,
  max_uma = excluded.max_uma,
  min_percent = excluded.min_percent,
  max_percent = excluded.max_percent,
  severity = excluded.severity,
  notes = excluded.notes,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  source_ids = excluded.source_ids,
  provision = excluded.provision,
  verification = excluded.verification,
  last_review_at = excluded.last_review_at,
  editorial_note = excluded.editorial_note,
  status = excluded.status;

insert into public.obligations (slug, title, summary, category, activities, steps, due_date, recurrence, source_ids, provision, verification, last_review_at, editorial_note, status, sort_order) values
  ('alta-sppld', 'Alta y registro en el portal SPPLD', 'Quien realiza una actividad vulnerable debe darse de alta en el padrón del SAT y habilitar su acceso al portal SPPLD para poder presentar avisos.', 'registro', '{}', '[{"id":"alta-sppld-1","texto":"Contar con e.firma vigente de la persona física o moral.","evidencia":"Constancia de e.firma"},{"id":"alta-sppld-2","texto":"Ingresar al portal SPPLD y seleccionar el alta en actividades vulnerables."},{"id":"alta-sppld-3","texto":"Registrar cada actividad vulnerable que se realiza y su fecha de inicio.","evidencia":"Acuse de alta"},{"id":"alta-sppld-4","texto":"Designar y registrar al representante encargado del cumplimiento.","evidencia":"Acuse de designación"},{"id":"alta-sppld-5","texto":"Resguardar el acuse de alta y los datos de acceso.","evidencia":"Acuse en PDF"}]'::jsonb, null, 'unica', array['lfpiorpi-vigente','sppld-portal']::text[], 'Art. 18, fracción I', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 0),
  ('representante-cumplimiento', 'Designación del representante encargado del cumplimiento', 'Las personas morales deben designar ante la autoridad a un representante encargado del cumplimiento, con facultades suficientes y datos actualizados.', 'gobierno', '{}', '[{"id":"representante-cumplimiento-1","texto":"Elegir a una persona con nivel jerárquico y facultades suficientes."},{"id":"representante-cumplimiento-2","texto":"Formalizar la designación en el órgano de gobierno.","evidencia":"Acta de designación"},{"id":"representante-cumplimiento-3","texto":"Registrar la designación en el portal del SAT.","evidencia":"Acuse de registro"},{"id":"representante-cumplimiento-4","texto":"Actualizar el registro cuando cambie la persona designada."}]'::jsonb, null, 'unica', array['lfpiorpi-vigente']::text[], 'Art. 20', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 1),
  ('identificacion-cliente', 'Identificación del cliente o usuario', 'Antes o al momento de realizar el acto, hay que identificar de forma directa al cliente o usuario y verificar su identidad con documentos válidos.', 'identificacion', '{}', '[{"id":"identificacion-cliente-1","texto":"Recabar los datos generales de la persona física o moral.","evidencia":"Formato de identificación"},{"id":"identificacion-cliente-2","texto":"Verificar la identidad con identificación oficial vigente.","evidencia":"Copia de identificación"},{"id":"identificacion-cliente-3","texto":"Solicitar por escrito si actúa por cuenta propia o de un tercero.","evidencia":"Manifestación firmada"},{"id":"identificacion-cliente-4","texto":"Documentar la actividad u ocupación y el origen de los recursos."}]'::jsonb, null, null, array['lfpiorpi-vigente']::text[], 'Art. 18, fracción I', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 2),
  ('expedientes', 'Integración y actualización de expedientes', 'Cada cliente identificado requiere un expediente único de identificación, actualizado y disponible para la autoridad.', 'expediente', '{}', '[{"id":"expedientes-1","texto":"Crear el expediente único al identificar al cliente."},{"id":"expedientes-2","texto":"Incorporar la documentación soporte de cada operación."},{"id":"expedientes-3","texto":"Revisar y actualizar los datos cuando cambien las circunstancias del cliente."},{"id":"expedientes-4","texto":"Documentar la fecha y responsable de cada actualización.","evidencia":"Bitácora de expediente"}]'::jsonb, null, 'semestral', array['lfpiorpi-vigente']::text[], 'Art. 18, fracción II', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 3),
  ('beneficiario-controlador', 'Identificación del beneficiario controlador', 'Hay que preguntar y documentar quién es la persona física que finalmente se beneficia o controla al cliente, incluso cuando el control es indirecto.', 'identificacion', '{}', '[{"id":"beneficiario-controlador-1","texto":"Solicitar por escrito la manifestación del cliente sobre su beneficiario controlador.","evidencia":"Manifestación firmada"},{"id":"beneficiario-controlador-2","texto":"Reconstruir la cadena de propiedad hasta llegar a personas físicas.","evidencia":"Organigrama corporativo"},{"id":"beneficiario-controlador-3","texto":"Evaluar el control por medios distintos a la propiedad accionaria."},{"id":"beneficiario-controlador-4","texto":"Documentar los casos en que no fue posible determinarlo y las medidas tomadas."}]'::jsonb, null, null, array['lfpiorpi-vigente']::text[], 'Art. 18, fracción III', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 4),
  ('conservacion-diez-anios', 'Conservación de información por diez años', 'La información, documentación y soportes de las operaciones y de la identificación deben conservarse por diez años.', 'conservacion', '{}', '[{"id":"conservacion-diez-anios-1","texto":"Definir el repositorio y el formato de conservación."},{"id":"conservacion-diez-anios-2","texto":"Garantizar respaldo y recuperación de la información.","evidencia":"Política de respaldo"},{"id":"conservacion-diez-anios-3","texto":"Controlar accesos y registrar consultas.","evidencia":"Bitácora de accesos"},{"id":"conservacion-diez-anios-4","texto":"Documentar el criterio de cómputo del plazo de diez años."}]'::jsonb, null, null, array['lfpiorpi-vigente']::text[], 'Art. 18, fracción IV', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 5),
  ('avisos', 'Presentación de avisos a más tardar el día 17', 'Los avisos por operaciones que alcanzan el umbral se presentan a más tardar el día 17 del mes siguiente a aquel en que ocurrió la operación.', 'avisos', '{}', '[{"id":"avisos-1","texto":"Identificar las operaciones del mes que alcanzan el umbral de aviso."},{"id":"avisos-2","texto":"Preparar el archivo con el formato oficial vigente."},{"id":"avisos-3","texto":"Revisar y aprobar internamente antes de enviar.","evidencia":"Registro de aprobación"},{"id":"avisos-4","texto":"Enviar por el portal SPPLD y resguardar el acuse.","evidencia":"Acuse de recepción"}]'::jsonb, null, 'mensual', array['lfpiorpi-vigente','sppld-portal']::text[], 'Art. 23', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 6),
  ('informes-en-ceros', 'Informes en ceros', 'Cuando en el periodo no hubo operaciones que alcanzaran el umbral de aviso, de todas formas debe presentarse el informe correspondiente.', 'avisos', '{}', '[{"id":"informes-en-ceros-1","texto":"Confirmar que en el periodo no hubo operaciones que alcanzaran el umbral."},{"id":"informes-en-ceros-2","texto":"Presentar el informe en ceros dentro del mismo plazo del día 17."},{"id":"informes-en-ceros-3","texto":"Resguardar el acuse.","evidencia":"Acuse de recepción"}]'::jsonb, null, 'mensual', array['lfpiorpi-vigente','sppld-portal']::text[], 'Art. 23', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 7),
  ('operaciones-inusuales', 'Avisos de operaciones inusuales en 24 horas', 'Cuando se detecta una operación inusual o preocupante, el aviso corre en un plazo mucho más corto que el ordinario. Incluye supuestos de operaciones intentadas.', 'avisos', '{}', '[{"id":"operaciones-inusuales-1","texto":"Documentar la alerta y el análisis que la originó.","evidencia":"Expediente del caso"},{"id":"operaciones-inusuales-2","texto":"Escalar al representante encargado del cumplimiento."},{"id":"operaciones-inusuales-3","texto":"Presentar el aviso dentro del plazo de 24 horas cuando proceda.","evidencia":"Acuse"},{"id":"operaciones-inusuales-4","texto":"Registrar la decisión aunque se concluya que no procede el aviso."}]'::jsonb, null, null, array['lfpiorpi-vigente']::text[], 'Art. 17 y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 8),
  ('enfoque-basado-riesgos', 'Metodología de enfoque basado en riesgos', 'Se debe contar con una metodología documentada que evalúe los riesgos del negocio y clasifique a los clientes en función de ellos.', 'riesgos', '{}', '[{"id":"enfoque-basado-riesgos-1","texto":"Identificar factores de riesgo: operación, cliente, geografía y canal de entrega."},{"id":"enfoque-basado-riesgos-2","texto":"Asignar ponderaciones y documentar el criterio.","evidencia":"Documento de metodología"},{"id":"enfoque-basado-riesgos-3","texto":"Definir mitigantes y su efecto en el puntaje."},{"id":"enfoque-basado-riesgos-4","texto":"Usar información de los últimos doce meses o proyecciones si no hay historial."},{"id":"enfoque-basado-riesgos-5","texto":"Revisar al menos una vez al año o cuando surjan nuevos riesgos.","evidencia":"Acta de revisión"}]'::jsonb, null, 'anual', array['lfpiorpi-vigente','dof-reglamento-2026','dof-acuerdo-115-2026']::text[], 'Reglamento y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 9),
  ('clasificacion-clientes', 'Clasificación de clientes por nivel de riesgo', 'Cada cliente debe quedar clasificado en riesgo bajo, medio o alto, y la clasificación debe revisarse periódicamente.', 'riesgos', '{}', '[{"id":"clasificacion-clientes-1","texto":"Aplicar la metodología a cada cliente al darlo de alta."},{"id":"clasificacion-clientes-2","texto":"Registrar el nivel resultante y su justificación.","evidencia":"Ficha de riesgo"},{"id":"clasificacion-clientes-3","texto":"Aplicar debida diligencia reforzada a los de riesgo alto."},{"id":"clasificacion-clientes-4","texto":"Revisar la clasificación al menos cada seis meses.","evidencia":"Bitácora de revisión"}]'::jsonb, null, 'semestral', array['lfpiorpi-vigente']::text[], 'Reglamento y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 10),
  ('perfil-transaccional', 'Perfil transaccional y su revisión semestral', 'Hay que construir un perfil esperado de operación para cada cliente y compararlo contra su comportamiento real de forma periódica.', 'riesgos', '{}', '[{"id":"perfil-transaccional-1","texto":"Definir el perfil esperado con base en la actividad declarada del cliente."},{"id":"perfil-transaccional-2","texto":"Comparar el comportamiento real contra el perfil."},{"id":"perfil-transaccional-3","texto":"Documentar y analizar las desviaciones relevantes.","evidencia":"Reporte de desviaciones"},{"id":"perfil-transaccional-4","texto":"Actualizar el perfil al menos cada seis meses."}]'::jsonb, null, 'semestral', array['lfpiorpi-vigente']::text[], 'Disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 11),
  ('personas-politicamente-expuestas', 'Personas políticamente expuestas (PEP)', 'Se debe identificar si el cliente, su beneficiario controlador o sus familiares cercanos son PEP y aplicar medidas reforzadas cuando así sea.', 'riesgos', '{}', '[{"id":"personas-politicamente-expuestas-1","texto":"Consultar al cliente y verificar contra fuentes de PEP."},{"id":"personas-politicamente-expuestas-2","texto":"Extender la revisión a familiares y asociados cercanos."},{"id":"personas-politicamente-expuestas-3","texto":"Obtener aprobación de un nivel jerárquico superior para iniciar o continuar la relación.","evidencia":"Aprobación documentada"},{"id":"personas-politicamente-expuestas-4","texto":"Aplicar monitoreo reforzado y revisión más frecuente."}]'::jsonb, null, null, array['lfpiorpi-vigente']::text[], 'Disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 12),
  ('manual-cumplimiento', 'Manual de políticas y procedimientos internos', 'El manual documenta cómo la organización cumple: identificación, expedientes, avisos, riesgos, capacitación, auditoría y conservación.', 'gobierno', '{}', '[{"id":"manual-cumplimiento-1","texto":"Redactar las políticas de identificación, expediente y conservación."},{"id":"manual-cumplimiento-2","texto":"Documentar los criterios de detección y escalamiento de operaciones inusuales."},{"id":"manual-cumplimiento-3","texto":"Aprobar el manual en el órgano de gobierno.","evidencia":"Acta de aprobación"},{"id":"manual-cumplimiento-4","texto":"Versionar el manual y conservar las versiones anteriores.","evidencia":"Control de versiones"}]'::jsonb, null, 'anual', array['lfpiorpi-vigente']::text[], 'Reglamento y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 13),
  ('mecanismos-automatizados', 'Mecanismos automatizados', 'La normativa exige contar con sistemas que apoyen la detección de umbrales, la acumulación, las alertas y la trazabilidad de las decisiones.', 'tecnologia', '{}', '[{"id":"mecanismos-automatizados-1","texto":"Concentrar las operaciones en una base única y consultable."},{"id":"mecanismos-automatizados-2","texto":"Configurar reglas de umbral y acumulación por actividad."},{"id":"mecanismos-automatizados-3","texto":"Generar alertas y dejar registro de su resolución.","evidencia":"Bitácora de alertas"},{"id":"mecanismos-automatizados-4","texto":"Conservar el historial de cambios de reglas con autor, fecha y motivo.","evidencia":"Control de versiones de reglas"}]'::jsonb, null, null, array['lfpiorpi-vigente','dof-reglamento-2026','dof-acuerdo-115-2026']::text[], 'Reglamento y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 14),
  ('capacitacion', 'Capacitación anual del personal', 'El personal involucrado debe recibir capacitación al menos una vez al año, con evidencia de asistencia y evaluación.', 'capacitacion', '{}', '[{"id":"capacitacion-1","texto":"Definir el programa anual y el personal alcanzado."},{"id":"capacitacion-2","texto":"Impartir la capacitación y registrar asistencia.","evidencia":"Lista de asistencia"},{"id":"capacitacion-3","texto":"Evaluar la comprensión de los participantes.","evidencia":"Resultados de evaluación"},{"id":"capacitacion-4","texto":"Conservar constancias por el plazo aplicable.","evidencia":"Constancias"}]'::jsonb, null, 'anual', array['lfpiorpi-vigente']::text[], 'Reglamento y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 15),
  ('investigacion-personal', 'Selección e investigación de personal', 'Debe existir un procedimiento documentado para investigar los antecedentes del personal que participa en las funciones de cumplimiento.', 'gobierno', '{}', '[{"id":"investigacion-personal-1","texto":"Definir el alcance de la investigación por puesto."},{"id":"investigacion-personal-2","texto":"Documentar la verificación de antecedentes y referencias.","evidencia":"Expediente de personal"},{"id":"investigacion-personal-3","texto":"Registrar la decisión de contratación y sus fundamentos."}]'::jsonb, null, null, array['lfpiorpi-vigente']::text[], 'Reglamento y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 16),
  ('auditoria-anual', 'Auditoría anual de cumplimiento', 'El programa de cumplimiento debe someterse a una auditoría con periodicidad anual, que genera hallazgos y un plan de remediación.', 'auditoria', '{}', '[{"id":"auditoria-anual-1","texto":"Seleccionar al auditor y verificar que cumpla los requisitos aplicables."},{"id":"auditoria-anual-2","texto":"Definir el alcance y el plan de trabajo.","evidencia":"Carta de alcance"},{"id":"auditoria-anual-3","texto":"Documentar hallazgos con su severidad.","evidencia":"Informe de auditoría"},{"id":"auditoria-anual-4","texto":"Establecer plan de remediación con responsables y fechas.","evidencia":"Plan de remediación"},{"id":"auditoria-anual-5","texto":"Dar seguimiento al cierre de cada hallazgo."}]'::jsonb, null, 'anual', array['lfpiorpi-vigente','dof-reglamento-2026','dof-acuerdo-115-2026']::text[], 'Reglamento y disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 17),
  ('dictamen', 'Dictamen y seguimiento de observaciones', 'El resultado de la auditoría se formaliza en un dictamen que se presenta ante la autoridad en el plazo aplicable.', 'auditoria', '{}', '[{"id":"dictamen-1","texto":"Integrar el dictamen con base en el informe de auditoría."},{"id":"dictamen-2","texto":"Aprobarlo en el órgano de gobierno.","evidencia":"Acta de aprobación"},{"id":"dictamen-3","texto":"Presentarlo en el plazo aplicable y resguardar el acuse.","evidencia":"Acuse"},{"id":"dictamen-4","texto":"Dar seguimiento a las observaciones hasta su cierre."}]'::jsonb, null, 'anual', array['lfpiorpi-vigente']::text[], 'Disposiciones de carácter general', 'fuente_secundaria', '2026-08-11'::date, 'Pendiente de contraste literal contra el texto vigente y el Acuerdo 115/2026.', 'revisado', 18)
on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  category = excluded.category,
  activities = excluded.activities,
  steps = excluded.steps,
  due_date = excluded.due_date,
  recurrence = excluded.recurrence,
  source_ids = excluded.source_ids,
  provision = excluded.provision,
  verification = excluded.verification,
  last_review_at = excluded.last_review_at,
  editorial_note = excluded.editorial_note,
  status = excluded.status,
  sort_order = excluded.sort_order;

insert into public.deadlines (id, due_date, end_date, title, description, obligations, officially_confirmed, source_ids, provision, verification, last_review_at, editorial_note, status) values
  ('vigencia-general', '2026-11-30'::date, null, 'Entrada en vigor del Acuerdo 115/2026', 'Fecha en que entran en vigor las reglas del Acuerdo 115/2026, que modifica las Reglas de Carácter General en materia de la LFPIORPI. A partir de aquí corren los plazos escalonados del resto del calendario.', array['manual-cumplimiento','enfoque-basado-riesgos']::text[], true, array['dof-acuerdo-115-2026']::text[], 'Artículo Primero Transitorio, Acuerdo 115/2026', 'oficial_verificado', '2026-08-11'::date, 'Fecha tomada de los artículos transitorios del Acuerdo 115/2026 publicado en el DOF.', 'publicado'),
  ('capacitacion-2027', '2027-01-01'::date, '2027-12-31'::date, 'Primer periodo anual de capacitación', 'El ejercicio 2027 completo constituye el primer periodo anual de capacitación bajo las nuevas reglas. La evidencia de asistencia y evaluación debe quedar documentada dentro de este periodo.', array['capacitacion']::text[], true, array['dof-acuerdo-115-2026']::text[], 'Artículos Transitorios, Acuerdo 115/2026', 'oficial_verificado', '2026-08-11'::date, 'Fecha tomada de los artículos transitorios del Acuerdo 115/2026 publicado en el DOF.', 'publicado'),
  ('ebr-manual-2027', '2027-03-01'::date, null, 'Metodología de riesgos, manual y expedientes', 'A partir de esta fecha la metodología de enfoque basado en riesgos debe estar disponible para la autoridad, alimentada con datos del año anterior, y el manual debe incorporarla. También aplican en esta fecha las reglas sobre clasificación de clientes, expedientes, beneficiario controlador y los procedimientos de selección de personal para nuevas contrataciones.', array['enfoque-basado-riesgos','manual-cumplimiento','clasificacion-clientes','expedientes','beneficiario-controlador','investigacion-personal']::text[], true, array['dof-acuerdo-115-2026']::text[], 'Artículos Transitorios, Acuerdo 115/2026', 'oficial_verificado', '2026-08-11'::date, 'Fecha tomada de los artículos transitorios del Acuerdo 115/2026 publicado en el DOF.', 'publicado'),
  ('psav-actualizacion', '2027-05-30'::date, null, 'Actualización de proveedores de servicios de activos virtuales', 'Plazo de seis meses contados desde la entrada en vigor. El texto oficial fija el plazo en meses, no una fecha calendario: esta fecha es un cálculo orientativo y debe confirmarse contra el transitorio aplicable.', '{}', false, array['dof-acuerdo-115-2026']::text[], 'Artículos Transitorios, Acuerdo 115/2026 (plazo en meses)', 'no_verificado', '2026-08-11'::date, 'Fecha estimada a partir de un plazo en meses. No hay una fecha calendario en el texto oficial.', 'revisado'),
  ('mecanismos-automatizados-2027', '2027-06-01'::date, null, 'Mecanismos automatizados en operación', 'Fecha a partir de la cual los mecanismos automatizados deben estar operando: detección de umbrales, acumulación, alertas y trazabilidad de las decisiones.', array['mecanismos-automatizados']::text[], true, array['dof-acuerdo-115-2026']::text[], 'Artículos Transitorios, Acuerdo 115/2026', 'oficial_verificado', '2026-08-11'::date, 'Fecha tomada de los artículos transitorios del Acuerdo 115/2026 publicado en el DOF.', 'publicado'),
  ('notificaciones-electronicas', '2027-07-30'::date, null, 'Notificaciones electrónicas', 'Plazo de ocho meses desde la entrada en vigor para el esquema de notificaciones electrónicas. Fecha calculada a partir de un plazo en meses; requiere confirmación.', '{}', false, array['dof-acuerdo-115-2026']::text[], 'Artículos Transitorios, Acuerdo 115/2026 (plazo en meses)', 'no_verificado', '2026-08-11'::date, 'Fecha estimada a partir de un plazo en meses. No hay una fecha calendario en el texto oficial.', 'revisado'),
  ('consulta-pep-2', '2027-08-30'::date, null, 'Disponibilidad prevista de Consulta PEP 2.0', 'La herramienta Consulta PEP 2.0 está prevista en el art. 23 Quáter 1 y se ofrecerá en el portal de la UIF, con acceso mediante la e.firma registrada en el alta. El plazo oficial es de nueve meses desde la entrada en vigor; esta fecha es un cálculo orientativo y no una fecha publicada.', array['personas-politicamente-expuestas']::text[], false, array['dof-acuerdo-115-2026']::text[], 'Art. 23 Quáter 1 y Transitorios, Acuerdo 115/2026 (plazo en meses)', 'no_verificado', '2026-08-11'::date, 'Fecha estimada a partir de un plazo en meses. No hay una fecha calendario en el texto oficial.', 'revisado'),
  ('auditoria-2028', '2028-01-01'::date, '2028-12-31'::date, 'Primer periodo de auditoría anual', 'El ejercicio 2028 completo constituye el primer periodo sujeto a auditoría anual. La auditoría puede ser interna cuando el riesgo de la organización es bajo o medio; es obligatoriamente externa cuando el riesgo es alto.', array['auditoria-anual']::text[], true, array['dof-acuerdo-115-2026']::text[], 'Artículos Transitorios, Acuerdo 115/2026', 'oficial_verificado', '2026-08-11'::date, 'Fecha tomada de los artículos transitorios del Acuerdo 115/2026 publicado en el DOF.', 'publicado'),
  ('dictamen-2029', '2029-03-30'::date, null, 'Entrega del primer dictamen (ejercicio 2028)', 'El primer dictamen, correspondiente al ejercicio 2028, se entrega a más tardar el último día hábil de marzo de 2029. La norma habla de "último día hábil": la fecha exacta depende del calendario oficial de días inhábiles de ese año y debe confirmarse antes de usarla como fecha límite operativa.', array['dictamen']::text[], true, array['dof-acuerdo-115-2026']::text[], 'Artículos Transitorios, Acuerdo 115/2026', 'oficial_verificado', '2026-08-11'::date, 'Fecha tomada de los artículos transitorios del Acuerdo 115/2026 publicado en el DOF.', 'publicado')
on conflict (id) do update set
  due_date = excluded.due_date,
  end_date = excluded.end_date,
  title = excluded.title,
  description = excluded.description,
  obligations = excluded.obligations,
  officially_confirmed = excluded.officially_confirmed,
  source_ids = excluded.source_ids,
  provision = excluded.provision,
  verification = excluded.verification,
  last_review_at = excluded.last_review_at,
  editorial_note = excluded.editorial_note,
  status = excluded.status;

insert into public.provider_categories (slug, name, description, sort_order) values
  ('contadores', 'Contadores públicos', '', 0),
  ('abogados', 'Abogados', '', 1),
  ('consultores-pld', 'Consultores en PLD', '', 2),
  ('auditores-externos', 'Auditores externos', '', 3),
  ('auditores-internos', 'Auditores internos', '', 4),
  ('capacitadores', 'Capacitadores', '', 5),
  ('proveedores-kyc', 'Proveedores de KYC', '', 6),
  ('consulta-pep-listas', 'Consulta de PEP y listas', '', 7),
  ('software-cumplimiento', 'Software de cumplimiento', '', 8),
  ('despachos-multidisciplinarios', 'Despachos multidisciplinarios', '', 9)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order;

insert into public.feature_flags (key, description, enabled) values
  ('directorio_publico', 'Muestra el directorio profesional en el sitio público.', false),
  ('tienda_plantillas', 'Habilita la descarga de plantillas de pago.', false),
  ('area_privada', 'Habilita el registro abierto en el área privada de cumplimiento.', false),
  ('monitor_regulatorio', 'Ejecuta el monitor de fuentes oficiales por tarea programada.', true)
on conflict (key) do nothing;

select set_config('app.motivo_cambio', '', false);
